### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by KenKout** [nuqz/ac_similar_obj#1]
Hi, 
Thanks for sharing such a great project.
I'm new to OpenCV and ML, so may I ask you how can I use this ? Since I don't see any file likely to execute the code
Thanks

**Comment by KenKout** [comment]
Oh so this is the problems and we need to solve it ? Do you provide solution code ?

**Comment by nuqz** [comment]
@KenKout thank you for interest. At this moment this project only contains dataset and few dataset augmentations. To preview it, you need to run `src/dataset.ipynb` notebook file. 

Naive implementation (which doesn't solve the challenge) may be run from `src/naive_implementation.ipynb` notebook file.

If you are still interested, I can share my thoughts and couple of python functions on how to improve efficiency and accuracy. But this will require to transform challenge into other task and re-label whole dataset (not all manually, but many images).
